### ISSUE TITLE
callsign checkup against data bases - init fails

### ISSUE THREAD

**Issue by mike-hb** [dh1tw/pyhamtools#10]
I use the last github with the following errors
Python 3.6.1 (default, Mar 23 2017, 13:04:44) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhamtools import LookupLib, Callinfo
>>> my_lookuplib = LookupLib(lookuptype="clublogxml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 106, in __init__
    self._load_clublogXML(apikey=self._apikey, cty_file=self._lib_filename)
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 954, in _load_clublogXML
    apikey = apikey)
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 1025, in _download_file
    if not self._check_html_response(response):
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 1437, in _check_html_response
    raise APIKeyMissingError
pyhamtools.exceptions.APIKeyMissingError

or 
Python 3.6.1 (default, Mar 23 2017, 13:04:44) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhamtools import LookupLib, Callinfo
>>> my_lookuplib = LookupLib(lookuptype="countryfile")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 108, in __init__
    self._load_countryfile(cty_file=self._lib_filename)
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 995, in _load_countryfile
    cty_file = self._download_file(url=url)
  File "/usr/lib/python3.6/site-packages/pyhamtools/lookuplib.py", line 1047, in _download_file
    download_file.write(response.content)
TypeError: write() argument must be str, not bytes

**Comment by dh1tw** [comment]
Sorry, Pyhamtools is currently only compatible with python 2

**Comment by mike-hb** [comment]
Thanks for quick reply
